#index:
#    path: /
#    controller: App\Controller\DefaultController::index
catalinRoute:
    path: /catalinchinchisan
    controller: App\Controller\catalinCtrl::init

app_front:
  path: /
  controller: App\Controller\Bettina::getFrontPage

app_Bettina:
  path: /Bettina
  controller: App\Controller\Bettina::getPersonalPage

app_Test1:
  path: /test1
  controller: App\Controller\Bettina::getTest1Page

app_Test2:
  path: /test2
  controller: App\Controller\Bettina::getTest2Page

app_Test3:
  path: /test3
  controller: App\Controller\Bettina::getTest3Page

app_Test4:
  path: /test4
  controller: App\Controller\Bettina::getTest4Page


pojar_alexandru:
  path: /pojar_alexandru
  controller: App\Controller\PojarAlexandru::number

cristea_ioan:
  path: /cristea_ioan
  controller: App\Controller\CristeaIoan::number

bunulescu_stefan:
   path: /bunulescu_stefan
   controller: App\Controller\BunulescuStefan::index
